// Run with Playwright on NODE_PATH, or a locally installed playwright package.
// API responses are mocked: this verifies browser interactions, not backend integration.
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

async function main(){
  const browser = await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
    const page=await context.newPage();
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    const root={id:'root',name:'CheckoutService',type:'SERVICE',sourcePath:'src/CheckoutService.java',line:1,confidence:1,attributes:{}};
    const methods=Array.from({length:15},(_,i)=>({id:`m${i}`,name:`Worker.process${i}()`,type:'METHOD',sourcePath:'src/Worker.java',line:i+2,confidence:.9,attributes:{}}));
    const test={id:'test',name:'CheckoutServiceTest',type:'TEST',sourcePath:'test/CheckoutServiceTest.java',line:8,confidence:.9,attributes:{}};
    const systemExtra={id:'api',name:'GET /checkout',type:'API',sourcePath:'src/CheckoutController.java',line:12,confidence:.8,attributes:{}};
    const nodes=[root,...methods,test,systemExtra];
    const edges=methods.map((n,i)=>({source:i?methods[i-1].id:'root',target:n.id,type:'CALLS',confidence:.9}));
    edges.push({source:'m0',target:'m14',type:'CALLS',confidence:.6});
    edges.push({source:'root',target:'api',type:'EXPOSES',confidence:.8});
    const impactNodes=[...methods,test].map((n,i)=>({...n,depth:i<3?1:2,relation:'CALLS',direction:'DOWNSTREAM',endLine:n.line+1}));
    const paths=methods.map((n,i)=>({targetId:n.id,targetName:n.name,targetType:n.type,hopCount:i+1,pathConfidence:.8,steps:[root,...methods.slice(0,i+1)].map(s=>({...s,endLine:s.line+1,viaRelation:'CALLS',direction:'DOWNSTREAM'}))}));
    const result={changedNode:'root',changedNodeName:root.name,scope:'FEATURE',directImpact:impactNodes.slice(0,3),indirectImpact:impactNodes.slice(3),apis:[],entities:[],tests:[test.name],areas:[],riskScore:61,riskLevel:'HIGH',riskReasons:['Fixture review'],riskBreakdown:{'Test Gap':6},evidenceConfidence:.8,blastRadius:1,maxDepth:4,exploredNodes:17,paths,explanation:'브라우저 검증용 고정 응답'};
    const apiImpact={...systemExtra,depth:3,relation:'EXPOSES',direction:'DOWNSTREAM',endLine:13};
    const apiPath={targetId:'api',targetName:systemExtra.name,targetType:'API',hopCount:1,pathConfidence:.8,steps:[root,systemExtra].map(s=>({...s,endLine:s.line+1,viaRelation:'EXPOSES',direction:'DOWNSTREAM'}))};
    const comparison={LOCAL:{...result,scope:'LOCAL',directImpact:impactNodes.slice(0,1),indirectImpact:[],paths:paths.slice(0,1),riskScore:22,riskLevel:'LOW'},FEATURE:result,SYSTEM:{...result,scope:'SYSTEM',indirectImpact:[...impactNodes.slice(3),apiImpact],paths:[...paths,apiPath],riskScore:72,riskLevel:'HIGH'}};
    let failImpact=false,reportRequests=0,expectToken=false,largeFixture=false;
    const githubReport={kind:'PR',owner:'spring-projects',repo:'spring-petclinic',reference:'42',baseSha:'a'.repeat(40),headSha:'b'.repeat(40),declaredRevision:'',revisionStatus:'UNVERIFIED',mappingSide:'HEAD',warnings:['ZIP 버전 미확인'],files:[{filename:'src/CheckoutService.java',previousFilename:'',changeStatus:'modified',mappingStatus:'MAPPED_METHOD',reason:'HEAD 줄 좌표',startNodeIds:['root']},{filename:'src/Missing.java',previousFilename:'',changeStatus:'removed',mappingStatus:'UNMAPPED',reason:'ZIP에서 해당 파일을 찾지 못했습니다.',startNodeIds:[]}],results:[result],summary:{changedFiles:2,javaFiles:2,methodMappedFiles:1,fallbackFiles:0,unmappedJavaFiles:1,changedStarts:1,uniqueImpactNodes:16,uniqueStructuralNodes:1,maxStartRiskScore:61,tests:[{id:test.id,name:test.name,sourcePath:test.sourcePath,line:8,depth:2,confidence:.9,changedStarts:[root.name]}]}};
    const sourceVerification={status:'VERIFIED',revision:'b'.repeat(40),zipPrefix:'',localFiles:2,repositoryFiles:2,matchedFiles:2,changedFiles:0,missingFiles:0,extraFiles:0,message:'분석 대상 Java 파일 전체의 경로·바이트 내용이 커밋과 일치합니다.',differences:[]};
    await page.route('**/api/**',async route=>{
      const url=new URL(route.request().url());
      let body;
      if(url.pathname==='/api/health')body={status:'UP',service:'fixture',time:'',neo4jConfigured:false};
      else if(url.pathname.endsWith('/upload')){const shownNodes=largeFixture?[...nodes,...Array.from({length:510},(_,i)=>({id:`large${i}`,name:`Large.method${i}()`,type:'METHOD',sourcePath:'src/Large.java',line:i+1,confidence:.9,attributes:{}}))]:nodes;body={projectId:'fixture',analyzedClasses:2,nodeCount:shownNodes.length,edgeCount:edges.length,analysisDurationMs:12,controllers:0,services:1,repositories:0,entities:0,methods:shownNodes.filter(n=>n.type==='METHOD').length,apis:1,tests:1,nodes:shownNodes,edges,warnings:[]};}
      else if(url.pathname.endsWith('/impact-comparison'))body=comparison;
      else if(url.pathname.endsWith('/impact')){
        if(failImpact)return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({message:'Fixture request failed'})});
        body=result;
      }else if(url.pathname.endsWith('/github-pr-report')){
        reportRequests++;const request=route.request().postDataJSON();
        assert.equal(request.owner,'spring-projects');assert.equal(request.pullNumber,42);
        assert.equal(route.request().headers()['x-github-token'],expectToken?'fixture-secret':undefined);
        assert.equal(JSON.stringify(request).includes('fixture-secret'),false);
        body=request.uploadedRevision?{...githubReport,revisionStatus:'DECLARED_MISMATCH',results:[],summary:{...githubReport.summary,methodMappedFiles:0,unmappedJavaFiles:2,changedStarts:0,uniqueImpactNodes:0,uniqueStructuralNodes:0,maxStartRiskScore:0,tests:[]}}:githubReport;
        if(!request.uploadedRevision&&request.verifySources)body={...githubReport,revisionStatus:'VERIFIED_JAVA_HEAD',warnings:['Java 소스만 검증했습니다.'],sourceVerification};
        if(request.uploadedRevision==='b'.repeat(40))body={...body,revisionStatus:'JAVA_CONTENT_MISMATCH',sourceVerification:{...sourceVerification,status:'MISMATCH',matchedFiles:1,changedFiles:1,message:'Java 소스 내용이 다릅니다.',differences:[{path:'src/CheckoutService.java',status:'CONTENT_CHANGED'}]}};
      }else throw new Error(`Unexpected API request ${url.pathname}`);
      await route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
    });
    await page.goto(process.env.UI_URL||'http://127.0.0.1:5173');
    await page.locator('input[type=file]').focus();
    assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('type')),'file','ZIP picker must be keyboard focusable');
    await page.locator('input[type=file]').setInputFiles({name:'fixture.zip',mimeType:'application/zip',buffer:Buffer.from('fixture')});
    await page.getByText('준비 완료 · fixture').waitFor();
    await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='변경점 분석 입력');
    await page.getByRole('button',{name:'영향 분석',exact:true}).click();
    await page.getByRole('region',{name:'핵심 분석 결과'}).getByRole('heading',{name:root.name}).waitFor();
    await page.waitForFunction(()=>document.activeElement?.classList.contains('result-snapshot'));
    await page.getByRole('region',{name:'핵심 분석 결과'}).getByText(test.name).waitFor();
    await page.locator('.snapshot-card').first().getByRole('button',{name:/Worker.process0/}).click();
    await page.getByRole('region',{name:'선택한 근거 경로'}).getByRole('heading',{name:'Worker.process0()'}).waitFor();
    assert.equal(await page.locator('.graph-card .node').count(),2);
    await page.getByRole('button',{name:'METHOD Worker.process0()'}).click();
    assert.equal(await page.locator('.result-snapshot').count(),1,'Graph inspection must preserve the analysis result');
    await page.locator('.graph-text-list>summary').click();
    await page.locator('.graph-text-list button').first().click();
    assert.equal(await page.locator('.result-snapshot').count(),1,'Text-list inspection must preserve the analysis result');
    await page.getByRole('button',{name:'전체 그래프로 돌아가기'}).click();
    await page.getByRole('button',{name:'상세 결과 보기'}).click();
    await page.waitForFunction(()=>Math.abs(document.querySelector('#detailed-results').getBoundingClientRect().top)<150);
    await page.getByRole('heading',{name:'이 변경에서 확인할 항목'}).waitFor();
    await page.getByRole('button',{name:'나머지 8개 모두 보기',exact:true}).click();
    assert.equal(await page.locator('.review-details>summary').filter({hasText:'METHOD'}).count(),15);
    await page.getByLabel('영향 후보 검색').fill('process14');
    assert.equal(await page.locator('.review-details>summary').filter({hasText:'METHOD'}).count(),1);
    await page.locator('.review-details>summary').filter({hasText:'METHOD'}).click();
    await page.getByRole('button',{name:'평가용 Node ID 복사'}).click();
    assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'m14');
    await page.getByLabel('영향 후보 검색').fill('no-match');
    await page.getByText('검색 조건에 맞는 영향 후보가 없습니다.').waitFor();
    await page.getByLabel('영향 후보 검색').fill('');
    await page.getByLabel('영향 유형').selectOption('TEST');
    assert.equal(await page.locator('.review-details>summary').filter({hasText:'TEST ·'}).count(),1);
    await page.getByLabel('영향 유형').selectOption('ALL');
    await page.getByRole('button',{name:'나머지 10개 경로 모두 보기'}).click();
    await page.locator('.review-details>summary').filter({hasText:'Worker.process14() · 15단계'}).click();
    await page.getByRole('button',{name:'그래프에서 이 경로 보기'}).last().click();
    assert.equal(await page.locator('.graph-card .node').count(),16,'Focused path must bypass the METHOD display cap');
    assert.equal(await page.locator('.graph-card .edge').count(),15,'Only consecutive path edges should be displayed');
    assert.equal(await page.locator('.evidence-path li').count(),16,'Evidence steps should include every node on the path');
    await page.getByRole('button',{name:'16단계 Worker.process14() 살펴보기'}).click();
    assert.equal(await page.locator('.result-snapshot').count(),1,'Inspecting an evidence step must preserve the analysis result');
    await page.getByRole('button',{name:'전체 그래프로 돌아가기'}).click();
    const output=path.resolve(__dirname,'../benchmark-output');fs.mkdirSync(output,{recursive:true});
    await page.screenshot({path:path.join(output,'review-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile page must not overflow horizontally');
    assert.equal(await page.locator('.workspace aside').evaluate(el=>el.getBoundingClientRect().top<document.querySelector('.graph-section').getBoundingClientRect().top),true,'Analysis controls should precede the graph on mobile');
    await page.screenshot({path:path.join(output,'review-mobile.png'),fullPage:true});
    await page.getByRole('button',{name:'3단계 비교'}).click();
    await page.getByRole('region',{name:'FEATURE 범위 증가분'}).getByText('새 영향 후보 15개').waitFor();
    await page.getByRole('region',{name:'SYSTEM 범위 증가분'}).getByText('새 영향 후보 1개').waitFor();
    await page.getByRole('region',{name:'SYSTEM 범위 증가분'}).getByText('API 1').waitFor();
    await page.screenshot({path:path.join(output,'comparison-mobile.png'),fullPage:true});
    await page.getByRole('region',{name:'FEATURE 범위 증가분'}).getByRole('button',{name:/Worker.process1/}).click();
    await page.getByRole('region',{name:'선택한 근거 경로'}).getByRole('heading',{name:'Worker.process1()'}).waitFor();
    assert.equal(await page.locator('.result-snapshot').count(),1,'Comparison evidence navigation must preserve the result');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Comparison must fit mobile width');
    failImpact=true;
    await page.getByRole('button',{name:'영향 분석',exact:true}).click();
    await page.getByText('Fixture request failed').waitFor();
    assert.equal(await page.getByRole('heading',{name:'이 변경에서 확인할 항목'}).count(),0,'A failed rerun must not leave a stale report');
    assert.equal(await page.locator('.result-snapshot').count(),0,'A failed rerun must not leave a stale summary');
    await page.locator('.github-box>summary').click();
    await page.getByLabel('GitHub PR 주소').fill('https://github.com/spring-projects/spring-petclinic/pull/42/files');
    await page.getByRole('button',{name:'PR 변경 Method 분석',exact:true}).click();
    await page.getByRole('region',{name:'핵심 분석 결과'}).getByRole('heading',{name:'PR #42'}).waitFor();
    await page.locator('.github-advanced>summary').click();
    await page.getByPlaceholder('Token (Private repo만)').fill('fixture-secret');
    expectToken=true;
    await page.getByRole('button',{name:'PR 변경 Method 분석',exact:true}).click();
    await page.getByRole('region',{name:'핵심 분석 결과'}).getByRole('heading',{name:'PR #42'}).waitFor();
    await page.getByRole('heading',{name:/PR 분석 요약/}).waitFor();
    await page.getByText('Java 소스 검증 완료 · HEAD',{exact:true}).waitFor();
    await page.getByLabel('변경 파일 검색').fill('Missing');
    assert.equal(await page.locator('.github-report .review-node').filter({hasText:'src/Missing.java'}).count(),1);
    const downloadEvent=page.waitForEvent('download');await page.getByTitle('JSON 결과 저장').click();
    const download=await downloadEvent;const exported=fs.readFileSync(await download.path(),'utf8');
    assert.equal(exported.includes('fixture-secret'),false);assert.equal(JSON.parse(exported).github.reference,'42');
    await page.getByLabel('ZIP 커밋 SHA').fill('c'.repeat(40));
    await page.getByRole('button',{name:'PR 변경 Method 분석',exact:true}).click();
    await page.getByText('입력한 커밋: 버전 불일치',{exact:true}).waitFor();
    assert.equal(await page.locator('.github-report').count(),1,'Zero mapped starts must still show the report');
    await page.getByRole('region',{name:'핵심 분석 결과'}).getByText('산출 안 됨').waitFor();
    await page.screenshot({path:path.join(output,'github-report-mobile.png'),fullPage:true});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.getByLabel('ZIP 커밋 SHA').fill('b'.repeat(40));
    await page.getByRole('button',{name:'PR 변경 Method 분석',exact:true}).click();
    await page.getByText('Java 소스 불일치 · 분석 중단',{exact:true}).waitFor();
    await page.getByRole('region',{name:'Java 소스 검증 결과'}).getByText('src/CheckoutService.java',{exact:true}).waitFor();
    await page.getByLabel('Java 소스 내용 검증',{exact:true}).uncheck();
    await page.getByLabel('ZIP 커밋 SHA').fill('');
    await page.getByRole('button',{name:'PR 변경 Method 분석',exact:true}).click();
    await page.getByText('ZIP 버전 미확인 · HEAD 가정',{exact:true}).waitFor();
    await page.getByLabel('GitHub PR 주소').fill('https://github.com.evil.test/a/b/pull/42');
    await page.getByRole('button',{name:'PR 변경 Method 분석',exact:true}).click();
    await page.waitForTimeout(100);assert.equal(reportRequests,5,'Invalid URLs must not reach the API');
    assert.equal(await page.locator('.result-snapshot').count(),1,'Invalid PR input must preserve the previous report');
    await page.locator('.graph-card .node').filter({hasText:'process0'}).first().click();
    assert.equal(await page.locator('.result-snapshot').count(),1,'Node inspection must keep the PR report');
    await page.getByRole('button',{name:'이 노드를 변경 시작점으로 선택'}).click();
    assert.equal(await page.locator('.result-snapshot').count(),0,'Changing the analysis start must clear old results');
    assert.equal(await page.locator('#selected-node').inputValue(),'m0');
    largeFixture=true;
    await page.locator('input[type=file]').setInputFiles({name:'large.zip',mimeType:'application/zip',buffer:Buffer.from('fixture-large')});
    await page.getByText('분석 가능한 노드 526개').waitFor();
    await page.getByLabel('분석 대상 검색').fill('Large.method509');
    await page.locator('#selected-node').selectOption('large509');
    await page.getByLabel('분석 대상 검색').fill('no-match');
    assert.equal(await page.locator('#selected-node').inputValue(),'large509','Filtering must retain the selected node');
    await page.getByText('검색 결과 0개 · 현재 선택은 목록에 유지').waitFor();
    assert.deepEqual(errors,[]);
    console.log('PASS: comparison deltas, large-node selection, evidence navigation, preserved results, keyboard upload, PR URL, mobile layout and stale-error state; mocked API');
  }finally{await browser.close()}
}
main().catch(e=>{console.error(e);process.exitCode=1});
